[2024-09-25T10:02:02.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T10:02:02.134+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_2.load.orderlines scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T10:02:02.161+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_2.load.orderlines scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-25T10:02:02.162+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T10:02:02.192+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): warehouse.step_2.load.orderlines> on 2024-09-24 00:00:00+00:00
[2024-09-25T10:02:02.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=536) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T10:02:02.215+0000] {standard_task_runner.py:72} INFO - Started process 547 to run task
[2024-09-25T10:02:02.217+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'warehouse.step_2.load.orderlines', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmpn_s9kj9d']
[2024-09-25T10:02:02.222+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask warehouse.step_2.load.orderlines
[2024-09-25T10:02:02.328+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.warehouse.step_2.load.orderlines scheduled__2024-09-24T00:00:00+00:00 [running]> on host 639d778bfb8f
[2024-09-25T10:02:02.518+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='warehouse.step_2.load.orderlines' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-25T10:02:02.521+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T10:02:02.554+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2024-09-25T10:02:02.762+0000] {base.py:84} INFO - Retrieving connection 'warehouse_db'
[2024-09-25T10:02:15.549+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-25T10:02:15.561+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T10:02:15.562+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=warehouse.step_2.load.orderlines, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240925T100202, end_date=20240925T100215
[2024-09-25T10:02:15.594+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-25T10:02:15.603+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
