[2024-10-03T07:48:03.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T07:48:03.176+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:48:03.193+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:48:03.194+0000] {taskinstance.py:2865} INFO - Starting attempt 36 of 36
[2024-10-03T07:48:03.214+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): warehouse.step_1.extract_transform.categories> on 2024-10-02 00:00:00+00:00
[2024-10-03T07:48:03.233+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=33467) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T07:48:03.235+0000] {standard_task_runner.py:72} INFO - Started process 33471 to run task
[2024-10-03T07:48:03.232+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'warehouse.step_1.extract_transform.categories', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '13576', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmpulnuukvi']
[2024-10-03T07:48:03.238+0000] {standard_task_runner.py:105} INFO - Job 13576: Subtask warehouse.step_1.extract_transform.categories
[2024-10-03T07:48:03.330+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [running]> on host 8c0d519f07a3
[2024-10-03T07:48:03.502+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='warehouse.step_1.extract_transform.categories' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='36' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2024-10-03T07:48:03.504+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T07:48:03.528+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-10-03T07:48:03.529+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02
[2024-10-03T07:48:03.608+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-10-03T07:48:12.034+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SparkContext: Running Spark version 3.5.3
[2024-10-03T07:48:12.041+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-10-03T07:48:12.042+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SparkContext: Java version 17.0.12
[2024-10-03T07:48:12.156+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-03T07:48:12.442+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceUtils: ==============================================================
[2024-10-03T07:48:12.444+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-03T07:48:12.446+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceUtils: ==============================================================
[2024-10-03T07:48:12.448+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SparkContext: Submitted application: Extract Transform - categories
[2024-10-03T07:48:12.503+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-03T07:48:12.526+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceProfile: Limiting resource is cpu
[2024-10-03T07:48:12.528+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-03T07:48:12.648+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SecurityManager: Changing view acls to: ***
[2024-10-03T07:48:12.649+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SecurityManager: Changing modify acls to: ***
[2024-10-03T07:48:12.651+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SecurityManager: Changing view acls groups to:
[2024-10-03T07:48:12.653+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SecurityManager: Changing modify acls groups to:
[2024-10-03T07:48:12.656+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-03T07:48:13.272+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO Utils: Successfully started service 'sparkDriver' on port 33021.
[2024-10-03T07:48:13.372+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO SparkEnv: Registering MapOutputTracker
[2024-10-03T07:48:13.470+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-03T07:48:13.531+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-03T07:48:13.532+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-03T07:48:13.543+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-03T07:48:13.595+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-ab94cc73-712a-4a01-b17d-ee7bebf92214
[2024-10-03T07:48:13.636+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-03T07:48:13.674+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-03T07:48:13.874+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-03T07:48:13.949+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-03T07:48:14.177+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-03T07:48:14.249+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO TransportClientFactory: Successfully created connection to spark-master/172.20.0.2:7077 after 43 ms (0 ms spent in bootstraps)
[2024-10-03T07:48:14.391+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241003074814-0032
[2024-10-03T07:48:14.399+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241003074814-0032/0 on worker-20241003061731-172.20.0.9-38803 (172.20.0.9:38803) with 2 core(s)
[2024-10-03T07:48:14.403+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO StandaloneSchedulerBackend: Granted executor ID app-20241003074814-0032/0 on hostPort 172.20.0.9:38803 with 2 core(s), 1024.0 MiB RAM
[2024-10-03T07:48:14.410+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41311.
[2024-10-03T07:48:14.411+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO NettyBlockTransferService: Server created on 8c0d519f07a3:41311
[2024-10-03T07:48:14.413+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-03T07:48:14.423+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8c0d519f07a3, 41311, None)
[2024-10-03T07:48:14.431+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO BlockManagerMasterEndpoint: Registering block manager 8c0d519f07a3:41311 with 434.4 MiB RAM, BlockManagerId(driver, 8c0d519f07a3, 41311, None)
[2024-10-03T07:48:14.436+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8c0d519f07a3, 41311, None)
[2024-10-03T07:48:14.442+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8c0d519f07a3, 41311, None)
[2024-10-03T07:48:14.481+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:14 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241003074814-0032/0 is now RUNNING
[2024-10-03T07:48:15.044+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:15 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-03T07:48:17.234+0000] {spark_submit.py:488} INFO - [2024-10-03T07:48:17.232+0000] {base.py:84} INFO - Retrieving connection 'staging_db'
[2024-10-03T07:48:17.251+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-03T07:48:17.272+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO SparkUI: Stopped Spark web UI at http://8c0d519f07a3:4040
[2024-10-03T07:48:17.279+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-03T07:48:17.283+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-03T07:48:17.309+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-03T07:48:17.354+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO MemoryStore: MemoryStore cleared
[2024-10-03T07:48:17.357+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO BlockManager: BlockManager stopped
[2024-10-03T07:48:17.416+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-03T07:48:17.422+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-03T07:48:17.474+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:17 INFO SparkContext: Successfully stopped SparkContext
[2024-10-03T07:48:17.640+0000] {spark_submit.py:488} INFO - categories doesn't have new data. Skipped...
[2024-10-03T07:48:17.642+0000] {spark_submit.py:488} INFO - [2024-10-03T07:48:17.641+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-03T07:48:18.252+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:18 INFO ShutdownHookManager: Shutdown hook called
[2024-10-03T07:48:18.254+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-8a13b1dd-b05f-4391-a311-9919876e32d0
[2024-10-03T07:48:18.258+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-b666b16e-b8a9-4c52-9780-8c814e5fab42
[2024-10-03T07:48:18.261+0000] {spark_submit.py:488} INFO - 24/10/03 07:48:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-b666b16e-b8a9-4c52-9780-8c814e5fab42/pyspark-1da496b9-45b5-4b4c-b07f-3bde916275bc
[2024-10-03T07:48:18.323+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 99.
[2024-10-03T07:48:18.329+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=warehouse.step_1.extract_transform.categories, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20241003T074803, end_date=20241003T074818
[2024-10-03T07:48:18.330+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: handle_failure
[2024-10-03T07:48:18.339+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: handle_failure
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 99.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/etl_pipeline/tasks/warehouse/main.py", line 19, in handle_failure
    raise AirflowSkipException("Skipping task due to no new data")
airflow.exceptions.AirflowSkipException: Skipping task due to no new data
[2024-10-03T07:48:18.365+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T07:48:18.366+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13576 for task warehouse.step_1.extract_transform.categories (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 99.; 33471)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 99.
[2024-10-03T07:48:18.390+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T07:48:18.419+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T07:48:18.422+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
