[2024-10-03T08:20:47.053+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T08:20:47.083+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T08:20:47.100+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T08:20:47.100+0000] {taskinstance.py:2865} INFO - Starting attempt 43 of 43
[2024-10-03T08:20:47.126+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): warehouse.step_1.extract_transform.categories> on 2024-10-02 00:00:00+00:00
[2024-10-03T08:20:47.141+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=38162) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T08:20:47.139+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'warehouse.step_1.extract_transform.categories', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '13604', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmpi3uy97lq']
[2024-10-03T08:20:47.143+0000] {standard_task_runner.py:105} INFO - Job 13604: Subtask warehouse.step_1.extract_transform.categories
[2024-10-03T08:20:47.143+0000] {standard_task_runner.py:72} INFO - Started process 38178 to run task
[2024-10-03T08:20:47.236+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [running]> on host 8c0d519f07a3
[2024-10-03T08:20:47.377+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='warehouse.step_1.extract_transform.categories' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='43' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2024-10-03T08:20:47.379+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T08:20:47.398+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-10-03T08:20:47.400+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories False 2024-10-02
[2024-10-03T08:20:47.455+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-10-03T08:20:55.215+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SparkContext: Running Spark version 3.5.3
[2024-10-03T08:20:55.220+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-10-03T08:20:55.221+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SparkContext: Java version 17.0.12
[2024-10-03T08:20:55.302+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-03T08:20:55.488+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceUtils: ==============================================================
[2024-10-03T08:20:55.489+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-03T08:20:55.490+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceUtils: ==============================================================
[2024-10-03T08:20:55.492+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SparkContext: Submitted application: Extract Transform - categories
[2024-10-03T08:20:55.544+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-03T08:20:55.559+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceProfile: Limiting resource is cpu
[2024-10-03T08:20:55.561+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-03T08:20:55.643+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SecurityManager: Changing view acls to: ***
[2024-10-03T08:20:55.644+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SecurityManager: Changing modify acls to: ***
[2024-10-03T08:20:55.646+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SecurityManager: Changing view acls groups to:
[2024-10-03T08:20:55.647+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SecurityManager: Changing modify acls groups to:
[2024-10-03T08:20:55.649+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:55 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-03T08:20:56.022+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO Utils: Successfully started service 'sparkDriver' on port 37947.
[2024-10-03T08:20:56.065+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO SparkEnv: Registering MapOutputTracker
[2024-10-03T08:20:56.119+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-03T08:20:56.152+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-03T08:20:56.153+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-03T08:20:56.159+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-03T08:20:56.190+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6d749696-0fd6-45b1-bcef-b7e8b35a3afa
[2024-10-03T08:20:56.221+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-03T08:20:56.256+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-03T08:20:56.438+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-03T08:20:56.524+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-03T08:20:56.705+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-03T08:20:56.772+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO TransportClientFactory: Successfully created connection to spark-master/172.20.0.2:7077 after 38 ms (0 ms spent in bootstraps)
[2024-10-03T08:20:56.919+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241003082056-0038
[2024-10-03T08:20:56.924+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241003082056-0038/0 on worker-20241003061731-172.20.0.9-38803 (172.20.0.9:38803) with 2 core(s)
[2024-10-03T08:20:56.929+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO StandaloneSchedulerBackend: Granted executor ID app-20241003082056-0038/0 on hostPort 172.20.0.9:38803 with 2 core(s), 1024.0 MiB RAM
[2024-10-03T08:20:56.943+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38833.
[2024-10-03T08:20:56.944+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO NettyBlockTransferService: Server created on 8c0d519f07a3:38833
[2024-10-03T08:20:56.947+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-03T08:20:56.957+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8c0d519f07a3, 38833, None)
[2024-10-03T08:20:56.962+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManagerMasterEndpoint: Registering block manager 8c0d519f07a3:38833 with 434.4 MiB RAM, BlockManagerId(driver, 8c0d519f07a3, 38833, None)
[2024-10-03T08:20:56.967+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8c0d519f07a3, 38833, None)
[2024-10-03T08:20:56.969+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8c0d519f07a3, 38833, None)
[2024-10-03T08:20:56.999+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:56 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241003082056-0038/0 is now RUNNING
[2024-10-03T08:20:57.461+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:57 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-03T08:20:59.088+0000] {spark_submit.py:488} INFO - [2024-10-03T08:20:59.085+0000] {base.py:84} INFO - Retrieving connection 'staging_db'
[2024-10-03T08:20:59.229+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:59 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-10-03T08:20:59.246+0000] {spark_submit.py:488} INFO - 24/10/03 08:20:59 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2024-10-03T08:21:02.771+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:02 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.20.0.9:52306) with ID 0,  ResourceProfileId 0
[2024-10-03T08:21:02.937+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:02 INFO BlockManagerMasterEndpoint: Registering block manager 172.20.0.9:39949 with 434.4 MiB RAM, BlockManagerId(0, 172.20.0.9, 39949, None)
[2024-10-03T08:21:03.746+0000] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2024-10-03T08:21:03.748+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 41, in _categories
[2024-10-03T08:21:03.750+0000] {spark_submit.py:488} INFO - df.write.csv(df_buffer, header=True, mode='overwrite')
[2024-10-03T08:21:03.751+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1864, in csv
[2024-10-03T08:21:03.753+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-10-03T08:21:03.754+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-10-03T08:21:03.755+0000] {spark_submit.py:488} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 330, in get_return_value
[2024-10-03T08:21:03.755+0000] {spark_submit.py:488} INFO - py4j.protocol.Py4JError: An error occurred while calling o52.csv. Trace:
[2024-10-03T08:21:03.756+0000] {spark_submit.py:488} INFO - py4j.Py4JException: Method csv([class java.util.ArrayList]) does not exist
[2024-10-03T08:21:03.756+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:321)
[2024-10-03T08:21:03.757+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:329)
[2024-10-03T08:21:03.757+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:274)
[2024-10-03T08:21:03.757+0000] {spark_submit.py:488} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-10-03T08:21:03.758+0000] {spark_submit.py:488} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-10-03T08:21:03.758+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-03T08:21:03.758+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-03T08:21:03.759+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-03T08:21:03.759+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.759+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.760+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.760+0000] {spark_submit.py:488} INFO - During handling of the above exception, another exception occurred:
[2024-10-03T08:21:03.760+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.761+0000] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2024-10-03T08:21:03.761+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 60, in <module>
[2024-10-03T08:21:03.761+0000] {spark_submit.py:488} INFO - ExtractTransform._categories(incremental, date)
[2024-10-03T08:21:03.762+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 48, in _categories
[2024-10-03T08:21:03.762+0000] {spark_submit.py:488} INFO - raise AirflowException(f"Error when extracting and transforming data from categories: {e}")
[2024-10-03T08:21:03.763+0000] {spark_submit.py:488} INFO - ***.exceptions.AirflowException: Error when extracting and transforming data from categories: An error occurred while calling o52.csv. Trace:
[2024-10-03T08:21:03.763+0000] {spark_submit.py:488} INFO - py4j.Py4JException: Method csv([class java.util.ArrayList]) does not exist
[2024-10-03T08:21:03.764+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:321)
[2024-10-03T08:21:03.765+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:329)
[2024-10-03T08:21:03.766+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:274)
[2024-10-03T08:21:03.767+0000] {spark_submit.py:488} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-10-03T08:21:03.767+0000] {spark_submit.py:488} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-10-03T08:21:03.768+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-03T08:21:03.768+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-03T08:21:03.769+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-03T08:21:03.769+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.770+0000] {spark_submit.py:488} INFO - 
[2024-10-03T08:21:03.771+0000] {spark_submit.py:488} INFO - [2024-10-03T08:21:03.750+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-03T08:21:04.298+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO SparkContext: Invoking stop() from shutdown hook
[2024-10-03T08:21:04.300+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-03T08:21:04.320+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO SparkUI: Stopped Spark web UI at http://8c0d519f07a3:4040
[2024-10-03T08:21:04.327+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-03T08:21:04.328+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-03T08:21:04.367+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-03T08:21:04.404+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO MemoryStore: MemoryStore cleared
[2024-10-03T08:21:04.406+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO BlockManager: BlockManager stopped
[2024-10-03T08:21:04.423+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-03T08:21:04.428+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-03T08:21:04.461+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO SparkContext: Successfully stopped SparkContext
[2024-10-03T08:21:04.462+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO ShutdownHookManager: Shutdown hook called
[2024-10-03T08:21:04.464+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-f036aabd-e79d-4216-b0c1-710fa9e9d805/pyspark-65df945b-2e60-4ba2-a3db-ec3cb0bafb7e
[2024-10-03T08:21:04.470+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-f036aabd-e79d-4216-b0c1-710fa9e9d805
[2024-10-03T08:21:04.476+0000] {spark_submit.py:488} INFO - 24/10/03 08:21:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-bc20e70f-4def-4805-9ed8-07c425c4e8c3
[2024-10-03T08:21:04.584+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories False 2024-10-02. Error code is: 1.
[2024-10-03T08:21:04.595+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=warehouse.step_1.extract_transform.categories, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20241003T082047, end_date=20241003T082104
[2024-10-03T08:21:04.595+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_notifier
[2024-10-03T08:21:04.599+0000] {baseoperator.py:405} WARNING - SlackWebhookOperator.execute cannot be called outside TaskInstance!
[2024-10-03T08:21:04.603+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/slack/hooks/slack_webhook.py:42 UserWarning: You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration. See: https://api.slack.com/messaging/webhooks#advanced_message_formatting. It is possible to change this values only in Legacy Slack Integration Incoming Webhook: https://api.slack.com/legacy/custom-integrations/messaging/webhooks#legacy-customizations
[2024-10-03T08:21:04.617+0000] {base.py:84} INFO - Retrieving connection 'slack_notifier'
[2024-10-03T08:21:05.090+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T08:21:05.091+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13604 for task warehouse.step_1.extract_transform.categories (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories False 2024-10-02. Error code is: 1.; 38178)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories False 2024-10-02. Error code is: 1.
[2024-10-03T08:21:05.147+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T08:21:05.175+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T08:21:05.178+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
